name: musicxml_parser_example
description: A command-line example for the musicxml_parser package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  musicxml_parser:
    path: ../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
