name: musicxml_parser
description: A pure Dart package for parsing MusicXML files into Dart objects.
version: 0.1.0
homepage: https://github.com/stevezhaoUS/musicxml_parser

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.0
  xml: ^6.5.0
  archive: ^4.0.7
  dart_console: ^4.1.2

  collection: any
dev_dependencies:
  build_runner: ^2.4.7
  lint: ^2.3.0
  mockito: ^5.4.4
  test: ^1.24.0
  coverage: ^1.7.2
