// Mocks generated by Mockito 5.4.6 from annotations
// in musicxml_parser/test/parser/measure_parser_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:musicxml_parser/src/models/note.dart' as _i4;
import 'package:musicxml_parser/src/parser/attributes_parser.dart' as _i6;
import 'package:musicxml_parser/src/parser/note_parser.dart' as _i3;
import 'package:musicxml_parser/src/utils/warning_system.dart' as _i2;
import 'package:xml/xml.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWarningSystem_0 extends _i1.SmartFake implements _i2.WarningSystem {
  _FakeWarningSystem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NoteParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteParser extends _i1.Mock implements _i3.NoteParser {
  MockNoteParser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WarningSystem get warningSystem => (super.noSuchMethod(
        Invocation.getter(#warningSystem),
        returnValue: _FakeWarningSystem_0(
          this,
          Invocation.getter(#warningSystem),
        ),
      ) as _i2.WarningSystem);

  @override
  _i4.Note? parse(
    _i5.XmlElement? element,
    int? parentDivisions,
    String? partId,
    String? measureNumber,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #parse,
        [
          element,
          parentDivisions,
          partId,
          measureNumber,
        ],
      )) as _i4.Note?);
}

/// A class which mocks [AttributesParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttributesParser extends _i1.Mock implements _i6.AttributesParser {
  MockAttributesParser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> parse(
    _i5.XmlElement? element,
    String? partId,
    String? measureNumber,
    int? currentDivisions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #parse,
          [
            element,
            partId,
            measureNumber,
            currentDivisions,
          ],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
