name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1.5.0
        with:
          sdk: 'stable'

      - name: Get dependencies
        run: dart pub get

      - name: Check package health
        run: dart pub global activate pana && dart pub global run pana --no-warning

      - name: Check documentation coverage
        run: |
          dart pub global activate dartdoc
          dart doc --validate-links

      - name: Run additional lints
        run: |
          dart pub global activate dcm
          dart pub global run dcm:metrics analyze lib --fatal-style --fatal-performance --fatal-warnings

      - name: Check for outdated dependencies
        run: dart pub outdated

      - name: Run tests with coverage
        run: |
          dart pub global activate coverage
          dart test --coverage=coverage
          dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

      - name: Verify pub publish
        run: dart pub publish --dry-run
